packages:
- name: cron
  environment:
    # This is required for the environment variable from the .env file to
    # actually get deployed. Documentation is unclear as to why, but likely for
    # security reasons to only explicitly allow known variables.
    CRON_URL: "${CRON_URL}"
  functions:
  - name: pinger
    binary: false
    runtime: 'php:default'
    web: false
    limits:
      # Max execution time in milliseconds.
      timeout: 5000
      # Max memory in megabytes.
      memory: 128
    triggers:
    - name: cron
      sourceType: scheduler
      sourceDetails:
        # Every 15 minutes by default. Edit as needed.
        cron: "*/15 * * * *"
